package com.fedex.intl.cd.data;
// Generated Class:         MsgId
// Generated on:            Thu Aug 16 10:41:50 MDT 2018
// Generated by:            217480
// Generated on OS:         Windows 7
// Generated on OS Version: 6.1
// Generated on VM:         Java HotSpot(TM) 64-Bit Server VM
// Generated on VM Vendor:  Oracle Corporation
// Generated on VM Version: 25.131-b11
// Generated by Component:  rmtc.stateGenerator.StateGenerator
// State Generater Version: $Revision: 39539 $
// State Version:           null

//-------------------------------------------------------------------
//  Below is the input fragment that was parsed to generate this file
//-------------------------------------------------------------------
//<xml-fragment generate="true" type="MsgId" packageName="com.fedex.intl.cd.data">
//  <stat:Attribute getterName="getMsgId" setterName="setMsgId" name="MsgId" type="int" fieldID="3001" xmlns:stat="file://rmtc/stateGenerator/StateConfig"/>
//</xml-fragment>
//-------------------------------------------------------------------
/**
 */
public class MsgId extends MsgIdBase implements java.io.Serializable, java.lang.Cloneable, Comparable, rmtc.util.TemplateParserDataSourceInterface
{
}
